spring.application.name=MyWeb
server.port=8081
################ Log 相關設定 ################
# console 的日志输出格式 顏色
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
#---H2 database DataSource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#---http://localhost:8081/h2-console
spring.h2.console.enabled=true
#---Hibernate automatically updates the schema and data
spring.jpa.hibernate.ddl-auto=update
#---prevent redundant validation. This property tells Spring Boot + JPA (Hibernate) to disable automatic bean validation during persistence operations (encodedPassword vs confirmPassword). MVC already validated during registration before sending to the persistent layer.---
spring.jpa.properties.javax.persistence.validation.mode=none
#---set Spring Data REST API and hal explorer basepath
spring.data.rest.basePath=/spring-data-api
#---enable all actuator endpoints---
management.endpoints.web.base-path=/myWeb/actuator
management.endpoints.web.exposure.include=*
management.server.port=8081
#---SpringBoot actuator admin server configuration
spring.boot.admin.client.url=http://localhost:8083
spring.boot.admin.client.instance.metadata.user.name=admin@gmail.com
spring.boot.admin.client.instance.metadata.user.password=admin
#---Custom Properties ---
#setting number of items per page in viewing contact messages
myweb.paginationPageSize=5